deman_avtopodbor/deman_avtopodbor/urls.py
from django.contrib import admin
from django.urls import path, include
from search.views import IndexView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('search/', include('search.urls', namespace='search')),
    path("users/", include('users.urls', namespace='users')),
]

deman_avtopodbor/search/urls.py
from django.urls import path
from search.views import SearchCarListView, IndexView

app_name = 'search'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('search/', SearchCarListView.as_view(), name='search')
]

deman_avtopodbor/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import UserLoginView, UserRegistrationView

app_name = 'users'


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegistrationView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout')
]

deman_avtopodbor/search/models.py
from django.db import models


class CarBrand(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

class CarModel(models.Model):
    name = models.CharField(max_length=64)
    year = models.DecimalField(max_digits=10, decimal_places=0)
    price = models.DecimalField(max_digits=30, decimal_places=2)
    brand = models.ForeignKey(to=CarBrand, on_delete=models.CASCADE)
    link = models.URLField(max_length=200, blank=True)

deman_avtopodbor/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите адрес эл. почты'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4', 'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

deman_avtopodbor/common/views.py
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data()
        context['title'] = self.title
        return context

deman_avtopodbor/search/views.py
from django.shortcuts import render
from common.views import TitleMixin
from django.views.generic.list import ListView
from search.models import CarModel
from django.views.generic.base import TemplateView
from django.shortcuts import redirect


class IndexView(TitleMixin, TemplateView):
    template_name = 'search/index.html'
    title = 'Подбор авто'

    def home(request):
        if request.user.is_authenticated:
            context = {'show_search_link': True}
        else:
            context = {'show_login_link': True}
        return render(request, 'home.html', context)


# Класс представления для поиска автомобилей
class SearchCarListView(TitleMixin, ListView):
    # Модель, используемая для отображения данных
    model = CarModel
    # Имя шаблона, который будет использоваться для отображения данных
    template_name = 'search/search.html'
    # Заголовок страницы
    title = "Поиск"

deman_avtopodbor/users/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from common.views import TitleMixin
from users.forms import UserLoginForm, UserRegistrationForm


class UserLoginView(TitleMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = "Авторизация"





class UserRegistrationView(TitleMixin, CreateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')
    title = 'Регистрация'

    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)  # Перенаправляем на страницу авторизации

deman_avtopodbor/search/templates/search/about.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<title>RenArt</title>
<link rel="shortcut icon" href="a198cd0c_e2f0_4c99_ba51_342624a24db9_WP4_icon.ico" type="image/x-icon"/>
<style>
* {
  box-sizing: border-box;
}
a {
  color: #f56642;
}
h3, h2, h1 {
  font-family: sans-serif;
  text-align: center;
}
h1 {
  color: #f56642;
}
p {
  text-align: center;
  margin-right: 20%;
  margin-left: 20%;
}
.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 8%;
}
</style>
</head>
<body>
<img src = "https://raw.githubusercontent.com/micahlt/renart/master/77E4F938-6119-49F1-906D-33252AB195CD.png" align = "center" class = "center">
<h1><a href = "https://micahlt.github.io/renart/"><b>About RenArt</b></a></h1>
<p>RenArt was created by Micah Lindley when he was doing a difficult assignment in a history class. He couldn’t find one website to find basic information on Renaissance artwork. So after he finished the assignment, he created the website that he was looking for. Thus RenArt was born.</p>

<h2>Новое поле</h2>
<p>Первая строка нового поля.</p>
<p>Вторая строка нового поля.</p>
<p>Третья строка нового поля.</p>
</body>
</html>

deman_avtopodbor/search/templates/search/index.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<title>{{ title }}</title>
<link rel='manifest' href='/manifest.json'>
<link rel="shortcut icon" href="a198cd0c_e2f0_4c99_ba51_342624a24db9_WP4_icon.ico" type="image/x-icon"/>
<link href = "https://fonts.googleapis.com/css?family=Nunito+Sans:400,900&display=swap" rel="stylesheet">
<style>
* {
  box-sizing: border-box;
  text-align: center;
}
a {
  color: #000000;
}
h3, h2, p {
  font-family: 'Nunito Sans', sans-serif;
  text-align: center;
}
h1:hover {
  animation-name: artshadow;
  animation-timing-function: ease-in-out;
  animation-fill-mode: both;
  animation-duration: 0.5s;
  animation-delay: 0.1s;
}
@keyframes artshadow {
  from {}
  to {text-shadow: 2px 2px 5px black;}
}
h1 {
  color: #000000;
  font-family: 'Nunito Sans', sans-serif;
  font-weight: 900;
}
.center {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 20%;
}
</style>
</head>
{% if request.user.is_authenticated %}
    <h3>Welcome, {{ request.user.username }}</h3>
    <a href="{% url 'users:logout' %}" class="btn btn-danger">Logout</a>
    <body>
    <img src = "https://sun9-49.userapi.com/impg/tqISUubG81dsgq8O-PAmxicuvphUdqqSY1jx3Q/pNUVBaqo1vA.jpg?size=500x345&quality=95&sign=3897121b3b154735a833d675cd377713&type=album" align = "center" class = "center">
    <h1><a href = "https://github.com/"><b>ДимасПодбор</b></a></h1>
    <h2>--------------------------------</h2><h3><a href = "{% url 'search:search' %}">Найди свою ласточку</a>
    <script>
    let deferredPrompt = null;

    window.addEventListener('beforeinstallprompt', (e) => {
     // Prevent Chrome 67 and earlier from automatically showing the prompt
     e.preventDefault();
     // Stash the event so it can be triggered later.
     deferredPrompt = e;
    });

    async function install() {
     if (deferredPrompt) {
       deferredPrompt.prompt();
       console.log(deferredPrompt)
       deferredPrompt.userChoice.then(function(choiceResult){

         if (choiceResult.outcome === 'accepted') {
         console.log('Your PWA has been installed');
       } else {
         console.log('User chose to not install your PWA');
       }

       deferredPrompt = null;

       });


     }
    }
    </script>
    </body>
{% else %}
    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
    <body>
    <img src = "https://sun9-49.userapi.com/impg/tqISUubG81dsgq8O-PAmxicuvphUdqqSY1jx3Q/pNUVBaqo1vA.jpg?size=500x345&quality=95&sign=3897121b3b154735a833d675cd377713&type=album" align = "center" class = "center">
    <h1><a href = "{% url 'index' %}"><b>ДимасПодбор</b></a></h1>
    <h2>Тачка для вас, бабки для нас</h2><h3><a href = "{% url 'users:login' %}">Авторизироваться</a>
    <script>
    let deferredPrompt = null;

    window.addEventListener('beforeinstallprompt', (e) => {
     // Prevent Chrome 67 and earlier from automatically showing the prompt
     e.preventDefault();
     // Stash the event so it can be triggered later.
     deferredPrompt = e;
    });

    async function install() {
     if (deferredPrompt) {
       deferredPrompt.prompt();
       console.log(deferredPrompt)
       deferredPrompt.userChoice.then(function(choiceResult){

         if (choiceResult.outcome === 'accepted') {
         console.log('Your PWA has been installed');
       } else {
         console.log('User chose to not install your PWA');
       }

       deferredPrompt = null;

       });


     }
    }
    </script>
    </body>
{% endif %}
</html>

deman_avtopodbor/search/templates/search/search.html
{% load static humanize %}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<title>{{ title }}</title>
<link rel="shortcut icon" href="{% static 'static/a198cd0c_e2f0_4c99_ba51_342624a24db9_WP4_icon.ico'%}" type="image/x-icon"/>
<link href = "https://fonts.googleapis.com/css?family=Nunito+Sans:400,900&display=swap" rel="stylesheet">
<style>
* {
  box-sizing: border-box;
}
body,#artInput{text-align: center;}
#artInput {
  background-image: url('https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Vector_search_icon.svg/221px-Vector_search_icon.svg.png');
  background-position: 10px 10px;;
  background-repeat: no-repeat;
  background-size: 25px;
  width: 60%;
  font-size: 16px;
  padding: 12px 20px 12px 40px;
  border: 1px solid #ddd;
  margin-bottom: 12px;
  border-radius: 25px;
}
#artInput:focus {
  outline:none
}
#artTable {
  border-collapse: collapse;
  width: 85%;
  border: 1px solid #ddd;
  font-size: 18px;
  margin-bottom:40px;
}
#artTable th, #artTable td {
  text-align: left;
  padding: 12px;
  text-align: center;

}
#artTable tr {
  border-bottom: 1px solid #ddd;

}
#artTable tr.header, #artTable tr:hover {
  background-color: #f1f1f1;

}
a {
  color: #000000;
}

h2, h1, p {
  font-family: 'Nunito Sans', sans-serif;
}
h1:hover {
  animation-name: artshadow;
  animation-timing-function: ease-in-out;
  animation-fill-mode: both;
  animation-duration: 0.5s;
  animation-delay: 0.1s;
}

@keyframes artshadow {
  from {}
  to {text-shadow: 2px 2px 5px black;}
}
h1 {
  color: #f56642;
  transition: 0.3s;
}
</style>
</head>
<body>
<h1><a href="{% url 'index' %}"><b>АвтоПодбор</b></a></h1>
<h2>Выберай!</h2>
<div class="centerenter">
<input type="text" id="artInput" onkeyup="artFunction()" placeholder="Бренд, марка, цена" title="Work search">
</div>
<div class="tablesearch">
<table id="artTable" align="center">
<tr class="header">
<th style="width:25%">Brand</th>
<th style="width:25%">Model</th>
<th style="width:25%">Year</th>
<th style="width:25%">price</th>
</tr>
{% for car in object_list %}
    <tr>
        <td><a href="{{ car.link }}">{{ car.brand }}</a></td>
        <td>{{ car.name }}</td>
        <td>{{ car.year }}</td>
        <td>{{ car.price | intcomma }} руб.</td>
    </tr>
{% endfor %}
</table>
</div>
<p>this project was created and is maintained by <a href = "https://micahlt.github.io/">Micah Lindley</a>.&#32;Last updated 8/21/19.</p>
<script>function artFunction() {
  // Declare starting variables
  var input = document.getElementById("artInput");
  var filter = input.value.toUpperCase();
  var table = document.getElementById("artTable");
  var trs = table.tBodies[0].getElementsByTagName("tr");
  // Loop through rows
  for (var i = 0; i < trs.length; i++) {
    // Define the cells
    var tds = trs[i].getElementsByTagName("td");
    // hide the row
    trs[i].style.display = "none";
    // loop through row cells
    for (var i2 = 0; i2 < tds.length; i2++) {
      // if there's a match
      if (tds[i2].innerHTML.toUpperCase().indexOf(filter) > -1) {
        // show the row
        trs[i].style.display = "";
        // skip to the next row
        continue;
      }
    }
  }
}

</script>
</body>
</html>

deman_avtopodbor/users/templates/users/login.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ titile }}</title>
</head>
<body>
    <h2>Авторизация</h2>
    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Имя пользователя:</label><br>
        <input type="text" id="username" name="username" class="form-control py-4" placeholder="Введите имя пользователя"><br>
        <label for="password">Пароль:</label><br>
        <input type="password" id="password" name="password" class="form-control py-4" placeholder="Введите пароль"><br>
        <input type="submit" value="Войти">
    </form>
    <a href="{% url 'users:register' %}"><button>Зарегистрироваться</button></a>
</body>
</html>

deman_avtopodbor/users/templates/users/register.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
</head>
<body>
    <h2>Регистрация</h2>
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        <label for="first_name">Имя:</label><br>
        <input type="text" id="first_name" name="first_name" class="form-control py-4" placeholder="Введите имя"><br>
        <label for="last_name">Фамилия:</label><br>
        <input type="text" id="last_name" name="last_name" class="form-control py-4" placeholder="Введите фамилию"><br>
        <label for="username">Имя пользователя:</label><br>
        <input type="text" id="username" name="username" class="form-control py-4" placeholder="Введите имя пользователя"><br>
        <label for="email">Email:</label><br>
        <input type="email" id="email" name="email" class="form-control py-4" placeholder="Введите адрес эл. почты"><br>
        <label for="password1">Пароль:</label><br>
        <input type="password" id="password1" name="password1" class="form-control py-4" placeholder="Введите пароль"><br>
        <label for="password2">Подтверждение пароля:</label><br>
        <input type="password" id="password2" name="password2" class="form-control py-4" placeholder="Подтвердите пароль"><br>
        <input type="submit" value="Зарегистрироваться">
    </form>
</body>
</html>